/*
MIT License

Copyright (c) 2020-2024 1Password

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// SecretTemplate defines Go templates for generating secret data keys.
// Each key in Data is a secret data key, and its value is a Go template string
// that will be rendered using the 1Password item's fields as context.
type SecretTemplate struct {
	// Data is a map of secret data key names to Go template strings.
	// Templates can access fields via .Fields (flat map), .Sections (nested by section),
	// or .FieldsByID (by field ID).
	// +optional
	Data map[string]string `json:"data,omitempty"`
}

// ImagePullSecretConfig configures automatic dockerconfigjson generation for image pull secrets.
// When set, the operator constructs a properly formatted .dockerconfigjson from the specified
// 1Password item fields, and automatically sets the secret type to kubernetes.io/dockerconfigjson.
type ImagePullSecretConfig struct {
	// RegistryField is the label of the 1Password field containing the registry URL (e.g. "ghcr.io").
	RegistryField string `json:"registryField,omitempty"`
	// UsernameField is the label of the 1Password field containing the registry username.
	UsernameField string `json:"usernameField,omitempty"`
	// PasswordField is the label of the 1Password field containing the registry password or token.
	PasswordField string `json:"passwordField,omitempty"`
	// EmailField is the label of the 1Password field containing the email (optional).
	EmailField string `json:"emailField,omitempty"`
}

// OnePasswordItemSpec defines the desired state of OnePasswordItem
type OnePasswordItemSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	ItemPath string `json:"itemPath,omitempty"`

	// Template defines Go templates for generating custom secret data.
	// When set, the secret data will be generated by rendering the templates
	// instead of using the default 1:1 field-to-key mapping.
	// +optional
	Template *SecretTemplate `json:"template,omitempty"`

	// ImagePullSecret configures automatic dockerconfigjson generation.
	// When set, the operator builds a .dockerconfigjson from the 1Password item fields
	// mapped by the config, and sets the secret type to kubernetes.io/dockerconfigjson.
	// +optional
	ImagePullSecret *ImagePullSecretConfig `json:"imagePullSecret,omitempty"`
}

type OnePasswordItemConditionType string

const (
	// OnePasswordItemReady means the Kubernetes secret is ready for use.
	OnePasswordItemReady OnePasswordItemConditionType = "Ready"
)

type OnePasswordItemCondition struct {
	// Type of job condition, Completed.
	Type OnePasswordItemConditionType `json:"type"`
	// Status of the condition, one of True, False, Unknown.
	Status metav1.ConditionStatus `json:"status"`
	// Last time the condition transit from one status to another.
	// +optional
	LastTransitionTime metav1.Time `json:"lastTransitionTime,omitempty"`
	// Human-readable message indicating details about last transition.
	// +optional
	Message string `json:"message,omitempty"`
}

// OnePasswordItemStatus defines the observed state of OnePasswordItem
type OnePasswordItemStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	Conditions []OnePasswordItemCondition `json:"conditions"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].status`
// +kubebuilder:resource:shortName=opi

// OnePasswordItem is the Schema for the onepassworditems API
type OnePasswordItem struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Kubernetes secret type. More info: https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
	Type   string                `json:"type,omitempty"`
	Spec   OnePasswordItemSpec   `json:"spec,omitempty"`
	Status OnePasswordItemStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OnePasswordItemList contains a list of OnePasswordItem
type OnePasswordItemList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OnePasswordItem `json:"items"`
}

func init() {
	SchemeBuilder.Register(&OnePasswordItem{}, &OnePasswordItemList{})
}
