apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: onepassword-connect-operator
  name: onepassword-connect-operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: onepassword-connect-operator
