# This rule is not used by the project onepassword-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over onepassword.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: onepassworditem-admin-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: onepassword-connect-operator
    app.kubernetes.io/part-of: onepassword-connect-operator
    app.kubernetes.io/managed-by: kustomize
  name: onepassworditem-admin-role
rules:
  - apiGroups:
      - onepassword.com
    resources:
      - onepassworditems
    verbs:
      - '*'
  - apiGroups:
      - onepassword.com
    resources:
      - onepassworditems/status
    verbs:
      - get
