apiVersion: v1
kind: Service
metadata:
  name: onepassword-connect
  namespace: default
spec:
  type: NodePort
  selector:
    app: onepassword-connect
  ports:
    - port: 8080
      name: connect-api
      nodePort: 31080
    - port: 8081
      name: connect-sync
      nodePort: 31081
