name: Build and Test
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test
